### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by shabansamani** [tmgiii/prj-rev-bwfs-dasmoto#2]
While the price renders properly, it's not typically encouraged to use the \<strong> tag except to bold something, and even then it's not encouraged to overwrite <strong> using CSS rules, as this could interfere with other \<strong> tags as well.

I recommend wrapping them in a \<span> and giving it a class "price" instead.

https://github.com/tmgiii/prj-rev-bwfs-dasmoto/blob/e40d174f55b13926c85cf7b0f8b0d51fe2eaba58/Dasmoto's%20Arts%20%26%20Crafts/index.html#L24

https://github.com/tmgiii/prj-rev-bwfs-dasmoto/blob/e40d174f55b13926c85cf7b0f8b0d51fe2eaba58/Dasmoto's%20Arts%20%26%20Crafts/index.html#L36

https://github.com/tmgiii/prj-rev-bwfs-dasmoto/blob/e40d174f55b13926c85cf7b0f8b0d51fe2eaba58/Dasmoto's%20Arts%20%26%20Crafts/index.html#L48

**Comment by tmgiii** [comment]
Fixed
