### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by shabansamani** [tmgiii/prj-rev-bwfs-dasmoto#3]
Make sure you add a secondary font-family (sans-serif) in case the user doesn't have the Helvetica font loaded on their machine to ensure that the site renders the way you want to. 

https://github.com/tmgiii/prj-rev-bwfs-dasmoto/blob/e40d174f55b13926c85cf7b0f8b0d51fe2eaba58/Dasmoto's%20Arts%20%26%20Crafts/resources/style.css#L2

**Comment by tmgiii** [comment]
Fixed
